### ISSUE TITLE
Gemipedia - gemini:// frontend to Wikipedia

### ISSUE THREAD

**Issue by Veraellyunjie** [digitalblossom/alternative-frontends#35]
Gemipedia
[gemini://gemi.dev/cgi-bin/wp.cgi/](gemini://gemi.dev/cgi-bin/wp.cgi/)
or via http proxy:
https://portal.mozz.us/gemini/gemi.dev/cgi-bin/wp.cgi/

**Comment by digitalblossom** [comment]
Thanks for the suggestion! I hadn't heard of Gemini before so I read up on it, and apparently it was only introduced in 2019 as an alternative to HTTP. Since the list here is focussed on privacy, I'm not fully confident in including it because of it being as new and ambitious which suggests to me that it is not as stable as HTTP at this point. Although I'm sure it will be useful in the future.
