### ISSUE TITLE
WolfreeAlpha

### ISSUE THREAD

**Issue by apmechev** [digitalblossom/alternative-frontends#45]
Instances: https://wolfreealpha.glitch.me/#Web-App
URL: https://wolfreealpha.glitch.me/input/index.html
Replaces https://wolframalpha.com/

**Comment by digitalblossom** [comment]
Great find. I was halfway into adding it but ultimately decided against it because the project seems to be exploiting paid APIs which is very thin ice legally. They have several legal disclaimers in their documentation and the project apparently is on WolframAlpha's radar.

I don't want to risk this repo being DMCA'ed, which is what has happened in the past multiple times apparently, according to the documentation.

Either way, thanks for taking the time to suggest it!

**Comment by digitalblossom** [comment]
See here as well:

https://github.com/WolfreeAlpha/wolfree.lisp (taken down)
